version: '3.6'

networks:
  notelan:
    driver: bridge

volumes:
  postgresvl:

services:
  postgres:
    image: daroge-image/postgres-notedb:1.0
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - postgresvl:/var/lib/postgresql/data
    networks:
      - notelan

  noteapp:
    image: daroge-image/note-app:1.0
    container_name: noteapp
    environment:
      WAIT_HOSTS: postgres:5432
      WAIT_HOSTS_TIMEOUT: 1000
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 1000
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8008:8008"
    depends_on:
      - postgres
    networks:
      - notelan
