server:
  port: 8008
  jsp-servlet:
    registered: false
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://postgres:5432/notedb
    username: noteusr
    password: notepw
    driver-class-name: org.postgresql.Driver
postUri: "http://localhost:8008/notes/{id}"

vertx:
  postgresql:
    database: notedb
    port: 5432
    username: noteusr
    password: notepw
    host:


