server:
  port: 8008
  jsp-servlet:
    registered: false
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://postgres:5432/notedb
    username: noteusr
    password: notepw
    driver-class-name: org.postgresql.Driver

